# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: screego
before:
  hooks:
    - go mod download
    - go run hack/packr/packr.go
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
    goarm:
      - 6
      - 7
    flags:
      - '-tags="netgo osusergo"'
    ldflags:
      - '-s'
      - '-w'
      - '-X main.version={{.Version}}'
      - '-X main.commitHash={{.Commit}}'
      - '-X main.mode=prod'
archives:
  - files:
      - LICENSE
      - README.md
      - screego.config.example
    replacements:
      386: i386
    format_overrides:
      - goos: windows
        format: zip
checksum:
changelog:
  skip: true
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - screego
    image_templates:
      - "floriansdev/screego-dev:amd64-unstable"
      - "floriansdev/screego-dev:amd64-{{ .RawVersion }}"
      - "floriansdev/screego-dev:amd64-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goos: linux
    goarch: 386
    binaries:
      - screego
    goarm: ''
    image_templates:
      - "floriansdev/screego-dev:386-unstable"
      - "floriansdev/screego-dev:386-{{ .RawVersion }}"
      - "floriansdev/screego-dev:386-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goos: linux
    goarch: arm64
    goarm: ''
    binaries:
      - screego
    image_templates:
      - "floriansdev/screego-dev:arm64-unstable"
      - "floriansdev/screego-dev:arm64-{{ .RawVersion }}"
      - "floriansdev/screego-dev:arm64-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goos: linux
    goarch: arm
    goarm: 7
    binaries:
      - screego
    image_templates:
      - "floriansdev/screego-dev:armv7-unstable"
      - "floriansdev/screego-dev:armv7-{{ .RawVersion }}"
      - "floriansdev/screego-dev:armv7-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goos: linux
    goarch: arm
    goarm: 6
    binaries:
      - screego
    image_templates:
      - "floriansdev/screego-dev:armv6-unstable"
      - "floriansdev/screego-dev:armv6-{{ .RawVersion }}"
      - "floriansdev/screego-dev:armv6-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - goos: linux
    goarch: ppc64le
    goarm: ''
    binaries:
      - screego
    image_templates:
      - "floriansdev/screego-dev:ppc64le-unstable"
      - "floriansdev/screego-dev:ppc64le-{{ .RawVersion }}"
      - "floriansdev/screego-dev:ppc64le-{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
